# 数据库初始化
# 创建 SCHEMAS
CREATE SCHEMA IF NOT EXISTS WEB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

# 设置时区
SET GLOBAL TIME_ZONE='+8:00';

-- RBAC(ROLE-BASED ACCESS CONTROL) 权限模型
CREATE TABLE IF NOT EXISTS WEB.AUTH_USER
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '用户ID',
    USERNAME    VARCHAR(50)                  NULL COMMENT '角色名',
    PASSWORD    VARCHAR(50)                  NULL COMMENT '密码',
    REALNAME    VARCHAR(50)                  NULL COMMENT '真实姓名',
    EMAIL       VARCHAR(50)                  NULL COMMENT '邮箱',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '用户表';

CREATE TABLE IF NOT EXISTS WEB.AUTH_ROLE
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '角色ID',
    NAME        VARCHAR(50)                  NULL COMMENT '角色名',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '角色表';


CREATE TABLE IF NOT EXISTS WEB.AUTH_GROUP
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '用户组ID',
    NAME        VARCHAR(50)                  NULL COMMENT '用户组名',
    FID         VARCHAR(50)                  NULL COMMENT '父用户组ID',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '用户组表';


CREATE TABLE IF NOT EXISTS WEB.AUTHORITY
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '权限ID',
    NAME        VARCHAR(50)                  NULL COMMENT '权限类型',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '权限表';

CREATE TABLE IF NOT EXISTS WEB.AUTH_OPERATION
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '权限ID',
    NAME        VARCHAR(50)                  NULL COMMENT '权限类型',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '功能操作';

CREATE TABLE IF NOT EXISTS WEB.AUTH_MENU
(
    ID          BIGINT AUTO_INCREMENT UNIQUE NOT NULL
        PRIMARY KEY COMMENT '菜单ID',
    NAME        VARCHAR(50)                  NULL COMMENT '菜单名',
    URL         VARCHAR(100)                 NULL COMMENT '地址',
    PID         BIGINT   DEFAULT 0 COMMENT '父节点ID',
    STATUS      varchar(20)                  NULL comment '状态',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '菜单表';

CREATE TABLE IF NOT EXISTS WEB.AUTH_USER_GROUP
(
    USER_ID     BIGINT NOT NULL COMMENT '用户ID',
    GROUP_ID    BIGINT NOT NULL COMMENT '用户组ID',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT PK_USER_ID_GROUP_ID PRIMARY KEY (USER_ID, GROUP_ID),
    CONSTRAINT AUTH_USER_GROUP_AUTH_GROUP_GROUP_ID_ID_FK
        FOREIGN KEY (GROUP_ID) REFERENCES WEB.AUTH_GROUP (ID),
    CONSTRAINT AUTH_USER_GROUP_AUTH_USER_USER_ID_ID_FK
        FOREIGN KEY (USER_ID) REFERENCES WEB.AUTH_USER (ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '用户组与用户关联表';



CREATE TABLE IF NOT EXISTS WEB.AUTH_ROLE_GROUP
(
    ROLE_ID     BIGINT NOT NULL COMMENT '角色ID',
    GROUP_ID    BIGINT NOT NULL COMMENT '用户组ID',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT AUTH_ROLE_GROUP_AUTH_GROUP_GROUP_ID_ID_FK
        FOREIGN KEY (GROUP_ID) REFERENCES WEB.AUTH_GROUP (ID),
    CONSTRAINT AUTH_ROLE_GROUP_AUTH_ROLE_ROLE_ID_ID_FK
        FOREIGN KEY (ROLE_ID) REFERENCES WEB.AUTH_ROLE (ID),
    CONSTRAINT PK_ROLE_ID_GROUP_ID PRIMARY KEY (ROLE_ID, GROUP_ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '用户组与角色关联表';


CREATE TABLE IF NOT EXISTS WEB.AUTH_USER_ROLE
(
    ROLE_ID     BIGINT NOT NULL COMMENT '角色ID',
    USER_ID     BIGINT NOT NULL COMMENT '用户ID',
    CREATE_TIME DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT AUTH_ROLE_USER_AUTH_USER_USER_ID_ID_FK
        FOREIGN KEY (USER_ID) REFERENCES WEB.AUTH_USER (ID),
    CONSTRAINT AUTH_ROLE_USER_AUTH_ROLE_ROLE_ID_ID_FK
        FOREIGN KEY (ROLE_ID) REFERENCES WEB.AUTH_ROLE (ID),
    CONSTRAINT PK_ROLE_ID_USER_ID PRIMARY KEY (ROLE_ID, USER_ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '用户角色关联表';



CREATE TABLE IF NOT EXISTS WEB.AUTH_ROLE_AUTHORITY
(
    ROLE_ID      BIGINT NOT NULL COMMENT '角色ID',
    AUTHORITY_ID BIGINT NOT NULL COMMENT '权限ID',
    CREATE_TIME  DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT PK_ROLE_ID_AUTHORITY_ID PRIMARY KEY (ROLE_ID, AUTHORITY_ID),
    CONSTRAINT AUTH_ROLE_AUTHORITY_AUTHORITY_AUTHORITY_ID_ID_FK
        FOREIGN KEY (AUTHORITY_ID) REFERENCES WEB.AUTHORITY (ID),
    CONSTRAINT AUTH_ROLE_AUTHORITY_AUTH_ROLE_ROLE_ID_ID_FK
        FOREIGN KEY (ROLE_ID) REFERENCES WEB.AUTH_ROLE (ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '角色权限关联表';


CREATE TABLE IF NOT EXISTS WEB.AUTH_OPERATION_AUTHORITY
(
    OPERATION_ID BIGINT NOT NULL COMMENT '功能ID',
    AUTHORITY_ID BIGINT NOT NULL COMMENT '权限ID',
    CREATE_TIME  DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT PK_OPERATION_ID_AUTHORITY_ID PRIMARY KEY (OPERATION_ID, AUTHORITY_ID),
    CONSTRAINT AUTH_OPERATION_AUTHORITY_AUTHORITY_AUTHORITY_ID_ID_FK
        FOREIGN KEY (AUTHORITY_ID) REFERENCES WEB.AUTHORITY (ID),
    CONSTRAINT AUTH_OPERATION_AUTHORITY_AUTH_OPERATION_OPERATION_ID_ID_FK
        FOREIGN KEY (OPERATION_ID) REFERENCES WEB.AUTH_OPERATION (ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '权限操作关联表';


CREATE TABLE IF NOT EXISTS WEB.AUTH_MENU_AUTHORITY
(
    AUTHORITY_ID BIGINT NOT NULL COMMENT '权限ID',
    MENU_ID      BIGINT NOT NULL COMMENT '菜单ID',
    CREATE_TIME  DATETIME DEFAULT NOW() COMMENT '创建日期',
    CONSTRAINT PK_AUTHORITY_ID_MENU_ID PRIMARY KEY (MENU_ID, AUTHORITY_ID),
    CONSTRAINT AUTH_MENU_AUTHORITY_AUTHORITY_AUTHORITY_ID_ID_FK
        FOREIGN KEY (AUTHORITY_ID) REFERENCES WEB.AUTHORITY (ID),
    CONSTRAINT AUTH_MENU_AUTHORITY_AUTH_MENU_MENU_ID_ID_FK
        FOREIGN KEY (MENU_ID) REFERENCES WEB.AUTH_MENU (ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '权限菜单关联表';
