-- 主表结构定义
CREATE TABLE IF NOT EXISTS WORKITEM
(
    C_PK         BIGSERIAL PRIMARY KEY,
    C_URI        INTEGER NOT NULL,
    C_REV        INTEGER NOT NULL,
    C_DELETED    CHAR(1)   DEFAULT 'N',
    C_TYPE       VARCHAR(50),
    C_NAME       VARCHAR(255),
    C_TEXT_VALUE TEXT,
    C_STATUS     VARCHAR(50),
    C_PRIORITY   VARCHAR(20),
    FK_PROJECT   BIGINT,
    FK_AUTHOR    BIGINT,
    C_CREATED    TIMESTAMP DEFAULT NOW(),
    C_UPDATED    TIMESTAMP DEFAULT NOW(),
    C_DUEDATE    DATE
);
