server:
  port: 8081
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: xuin23.com
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      host: xuin23.com
      port: 8500
      discovery:
        service-name: @pom.artifactId@
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000